# Generated by Django 6.0.2 on 2026-03-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email для авторизации через код подтверждения', max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('CLIENT', 'Клиент')], db_index=True, default='CLIENT', max_length=20, verbose_name='Роль'),
        ),
    ]
