# Generated by Django 6.0.2 on 2026-03-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_phone_9474e8_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
