# Generated by Django 6.0.2 on 2026-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Номер телефона пользователя', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
