# Generated by Django 6.0.2 on 2026-03-11 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options_organization_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='count_services',
            field=models.IntegerField(default=0, verbose_name='Количество услуг'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('wash', 'Мойка'), ('tire', 'Шиномонтаж')], db_index=True, default='wash', max_length=20, verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='summary_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wheel_diameters',
            field=models.JSONField(blank=True, default=list, help_text='Массив диаметров дисков для шиномонтажа', verbose_name='Диаметры дисков'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_status'], name='organizatio_organiz_23073f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_d4294a_idx'),
        ),
    ]
