# Generated by Django 6.0.2 on 2026-03-19 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_count_services_organization_org_inn_and_more'),
        ('services', '0003_service_status_service_services_se_status_288ecc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('reason', models.CharField(blank=True, help_text='Например: Новый год, технический перерыв', max_length=255, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['organization', 'date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='organizatio_organiz_52434a_idx'), models.Index(fields=['date', 'is_active'], name='organizatio_date_043d1d_idx')],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('open_time', models.TimeField(help_text='Формат: HH:MM', verbose_name='Время открытия')),
                ('close_time', models.TimeField(help_text='Формат: HH:MM', verbose_name='Время закрытия')),
                ('break_start', models.TimeField(blank=True, help_text='Опционально', null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, help_text='Опционально', null=True, verbose_name='Конец перерыва')),
                ('slot_duration', models.IntegerField(default=30, help_text='Минимальный интервал для записи', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)], verbose_name='Длительность слота (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Расписание организации',
                'verbose_name_plural': 'Расписания организаций',
                'ordering': ['organization', 'weekday'],
                'indexes': [models.Index(fields=['organization', 'weekday'], name='organizatio_organiz_de1ed0_idx'), models.Index(fields=['organization', 'is_working_day'], name='organizatio_organiz_fa5f73_idx')],
                'unique_together': {('organization', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('available_from', models.TimeField(help_text='Время начала доступности услуги', verbose_name='Доступна с')),
                ('available_to', models.TimeField(help_text='Время окончания доступности услуги', verbose_name='Доступна до')),
                ('max_bookings_per_slot', models.IntegerField(default=1, help_text='Количество одновременных записей', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Макс. записей на слот')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Доступность услуги',
                'verbose_name_plural': 'Доступность услуг',
                'ordering': ['service', 'weekday'],
                'indexes': [models.Index(fields=['service', 'weekday'], name='organizatio_service_26172a_idx'), models.Index(fields=['service', 'is_active'], name='organizatio_service_083d80_idx')],
                'unique_together': {('service', 'weekday')},
            },
        ),
    ]
