# Generated by Django 6.0.2 on 2026-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_count_services_organization_org_inn_and_more'),
        ('services', '0002_serviceitem_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('ghost', 'Скрытая')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='services_se_status_288ecc_idx'),
        ),
    ]
