# Generated by Django 6.0.2 on 2026-03-12 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(help_text='Марка автомобиля, например: Toyota, BMW, Lada', max_length=100, verbose_name='Марка')),
                ('license_plate', models.CharField(db_index=True, help_text='Государственный регистрационный номер', max_length=20, unique=True, verbose_name='Госномер')),
                ('wheel_diameter', models.PositiveIntegerField(help_text='Диаметр диска в дюймах (число без R), например: 15, 16, 17', verbose_name='Диаметр шины')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='cars_car_user_id_912c06_idx'), models.Index(fields=['license_plate'], name='cars_car_license_fc57d8_idx')],
            },
        ),
    ]
