# Generated by Django 4.2.28 on 2026-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена'), ('DONE', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
