# Generated by Django 6.0.2 on 2026-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingitem_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='booking',
            name='wheel_diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диаметр диска'),
        ),
    ]
